// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PetCare_Web.Data;

#nullable disable

namespace PetCare_WinForm.Migrations
{
    [DbContext(typeof(PetCareContext))]
    partial class PetCareContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PetCare_Web.Models.BangLuongThang", b =>
                {
                    b.Property<string>("MaNv")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("MaNV");

                    b.Property<int>("Thang")
                        .HasColumnType("int");

                    b.Property<int>("Nam")
                        .HasColumnType("int");

                    b.Property<decimal?>("LuongCoBan")
                        .HasColumnType("decimal(18, 0)");

                    b.Property<DateOnly?>("NgayTinhLuong")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("date")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<decimal?>("Thuong")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18, 0)")
                        .HasDefaultValue(0m);

                    b.Property<int?>("TongGioCong")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<decimal?>("TongLuong")
                        .HasColumnType("decimal(18, 0)");

                    b.HasKey("MaNv", "Thang", "Nam")
                        .HasName("PK__BANG_LUO__563F494F5895B211");

                    b.ToTable("BANG_LUONG_THANG", (string)null);
                });

            modelBuilder.Entity("PetCare_Web.Models.BangPhanCa", b =>
                {
                    b.Property<string>("MaCa")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("MaNv")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("MaNV");

                    b.Property<DateOnly>("NgayLamViec")
                        .HasColumnType("date");

                    b.HasKey("MaCa", "MaNv", "NgayLamViec")
                        .HasName("PK__BANG_PHA__2965A1F9EF20C9C3");

                    b.HasIndex("MaNv");

                    b.ToTable("BANG_PHAN_CA", (string)null);
                });

            modelBuilder.Entity("PetCare_Web.Models.CaLamViec", b =>
                {
                    b.Property<string>("MaCa")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<TimeOnly?>("GioBd")
                        .HasColumnType("time")
                        .HasColumnName("GioBD");

                    b.Property<TimeOnly?>("GioKt")
                        .HasColumnType("time")
                        .HasColumnName("GioKT");

                    b.Property<string>("TenCa")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("MaCa")
                        .HasName("PK__CA_LAM_V__27258E7B48C600E7");

                    b.ToTable("CA_LAM_VIEC", (string)null);
                });

            modelBuilder.Entity("PetCare_Web.Models.ChamCong", b =>
                {
                    b.Property<string>("MaNv")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("MaNV");

                    b.Property<DateOnly>("NgayLamViec")
                        .HasColumnType("date");

                    b.Property<TimeOnly?>("Checkin")
                        .HasColumnType("time");

                    b.Property<TimeOnly?>("Checkout")
                        .HasColumnType("time");

                    b.HasKey("MaNv", "NgayLamViec")
                        .HasName("PK__CHAM_CON__E402F82157058E57");

                    b.ToTable("CHAM_CONG", (string)null);
                });

            modelBuilder.Entity("PetCare_Web.Models.ChiNhanh", b =>
                {
                    b.Property<string>("MaCn")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("MaCN");

                    b.Property<string>("DiaChi")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<TimeOnly?>("GioDongCua")
                        .HasColumnType("time");

                    b.Property<TimeOnly?>("GioMoCua")
                        .HasColumnType("time");

                    b.Property<string>("SoDienThoai")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("TenChiNhanh")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("MaCn")
                        .HasName("PK__CHI_NHAN__27258E0E5D479839");

                    b.ToTable("CHI_NHANH", (string)null);
                });

            modelBuilder.Entity("PetCare_Web.Models.ChiTietDd", b =>
                {
                    b.Property<string>("MaNv")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("MaNV");

                    b.Property<string>("MaDieuDong")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<DateOnly>("NgayBatDau")
                        .HasColumnType("date");

                    b.Property<string>("GhiChu")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("MaNv", "MaDieuDong", "NgayBatDau")
                        .HasName("PK__CHI_TIET__7F22DB102308F20A");

                    b.HasIndex("MaDieuDong", "NgayBatDau");

                    b.ToTable("CHI_TIET_DD", (string)null);
                });

            modelBuilder.Entity("PetCare_Web.Models.ChiTietDvSd", b =>
                {
                    b.Property<string>("MaHd")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("MaHD");

                    b.Property<string>("MaDv")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("MaDV");

                    b.Property<string>("GhiChu")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("MaHd", "MaDv")
                        .HasName("PK__CHI_TIET__4557FE855358D29E");

                    b.HasIndex("MaDv");

                    b.ToTable("CHI_TIET_DV_SD", (string)null);
                });

            modelBuilder.Entity("PetCare_Web.Models.ChiTietMuaHang", b =>
                {
                    b.Property<string>("MaSp")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("MaSP");

                    b.Property<string>("MaMuaHang")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<double?>("DonGia")
                        .HasColumnType("float");

                    b.Property<int?>("SoLuong")
                        .HasColumnType("int");

                    b.HasKey("MaSp", "MaMuaHang")
                        .HasName("PK__CHI_TIET__379539C237E85030");

                    b.HasIndex("MaMuaHang");

                    b.ToTable("CHI_TIET_MUA_HANG", (string)null);
                });

            modelBuilder.Entity("PetCare_Web.Models.ChiTietTiem", b =>
                {
                    b.Property<string>("MaVc")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("MaVC");

                    b.Property<string>("MaTiem")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<double?>("Gia")
                        .HasColumnType("float");

                    b.Property<int?>("LieuLuong")
                        .HasColumnType("int");

                    b.Property<DateOnly>("NgayTiem")
                        .HasColumnType("date");

                    b.HasKey("MaVc", "MaTiem")
                        .HasName("PK__CHI_TIET__F3E930B48D6A910A");

                    b.HasIndex("MaTiem");

                    b.ToTable("CHI_TIET_TIEM", (string)null);
                });

            modelBuilder.Entity("PetCare_Web.Models.ChiTietTiemThang", b =>
                {
                    b.Property<string>("MaVc")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("MaVC");

                    b.Property<string>("MaGoi")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<int>("LanTiem")
                        .HasColumnType("int");

                    b.Property<int?>("LieuLuong")
                        .HasColumnType("int");

                    b.Property<DateOnly?>("NgayTiem")
                        .HasColumnType("date");

                    b.HasKey("MaVc", "MaGoi", "LanTiem")
                        .HasName("PK__CHI_TIET__870B6AFF58BA0087");

                    b.HasIndex("MaGoi");

                    b.ToTable("CHI_TIET_TIEM_THANG", (string)null);
                });

            modelBuilder.Entity("PetCare_Web.Models.DanhGium", b =>
                {
                    b.Property<string>("MaDg")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("MaDG");

                    b.Property<string>("BinhLuan")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<double?>("DiemChatLuong")
                        .HasColumnType("float");

                    b.Property<double?>("DiemHaiLong")
                        .HasColumnType("float");

                    b.Property<double?>("DiemThaiDo")
                        .HasColumnType("float");

                    b.Property<string>("MaHd")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("MaHD");

                    b.Property<string>("MaKh")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("MaKH");

                    b.Property<string>("MaNv")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("MaNV");

                    b.Property<DateOnly?>("NgayDg")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("date")
                        .HasColumnName("NgayDG")
                        .HasDefaultValueSql("(getdate())");

                    b.HasKey("MaDg")
                        .HasName("PK__DANH_GIA__272586600BB6B5DA");

                    b.HasIndex("MaHd");

                    b.HasIndex("MaKh");

                    b.HasIndex("MaNv");

                    b.ToTable("DANH_GIA", (string)null);
                });

            modelBuilder.Entity("PetCare_Web.Models.DichVu", b =>
                {
                    b.Property<string>("MaDv")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("MaDV");

                    b.Property<string>("MaCn")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("MaCN");

                    b.Property<string>("MaTc")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("MaTC");

                    b.HasKey("MaDv")
                        .HasName("PK__DICH_VU__27258657F87657B6");

                    b.HasIndex("MaCn");

                    b.HasIndex("MaTc");

                    b.ToTable("DICH_VU", (string)null);
                });

            modelBuilder.Entity("PetCare_Web.Models.DvKham", b =>
                {
                    b.Property<string>("MaKham")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("BacSiPhuTrach")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("ChuanDoan")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<double?>("GiaKhamBenh")
                        .HasColumnType("float");

                    b.Property<DateOnly?>("NgayTaiKham")
                        .HasColumnType("date");

                    b.Property<string>("ToaThuoc")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TrieuChung")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("MaKham")
                        .HasName("PK__DV_KHAM__653E9A7AC2196A6D");

                    b.HasIndex("BacSiPhuTrach");

                    b.ToTable("DV_KHAM", (string)null);
                });

            modelBuilder.Entity("PetCare_Web.Models.DvMuaHang", b =>
                {
                    b.Property<string>("MaMuaHang")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("NhanVienBanHang")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.HasKey("MaMuaHang")
                        .HasName("PK__DV_MUA_H__0B031DE0DF3781DC");

                    b.HasIndex("NhanVienBanHang");

                    b.ToTable("DV_MUA_HANG", (string)null);
                });

            modelBuilder.Entity("PetCare_Web.Models.DvTiemPhongDonLe", b =>
                {
                    b.Property<string>("MaTiem")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("BacSiPhuTrach")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.HasKey("MaTiem")
                        .HasName("PK__DV_TIEM___4CC209DCBBA6217E");

                    b.HasIndex("BacSiPhuTrach");

                    b.ToTable("DV_TIEM_PHONG_DON_LE", (string)null);
                });

            modelBuilder.Entity("PetCare_Web.Models.DvTiemPhongTheoThang", b =>
                {
                    b.Property<string>("MaGoi")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("BacSiPhuTrach")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<double?>("GiaGoi")
                        .HasColumnType("float");

                    b.Property<DateOnly>("NgayDk")
                        .HasColumnType("date")
                        .HasColumnName("NgayDK");

                    b.Property<DateOnly>("NgayKt")
                        .HasColumnType("date")
                        .HasColumnName("NgayKT");

                    b.Property<int?>("SoThang")
                        .HasColumnType("int");

                    b.Property<string>("TenGoi")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("MaGoi")
                        .HasName("PK__DV_TIEM___3CD30F6905A424AC");

                    b.HasIndex("BacSiPhuTrach");

                    b.ToTable("DV_TIEM_PHONG_THEO_THANG", (string)null);
                });

            modelBuilder.Entity("PetCare_Web.Models.HoaDon", b =>
                {
                    b.Property<string>("MaHd")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("MaHD");

                    b.Property<string>("HinhThucThanhToan")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("KhuyenMai")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("MaCn")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("MaCN");

                    b.Property<string>("MaKh")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("MaKH");

                    b.Property<string>("MaNv")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("MaNV");

                    b.Property<DateOnly>("NgayLap")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("date")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<decimal?>("TongTien")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18, 0)")
                        .HasDefaultValue(0m);

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("MaHd")
                        .HasName("PK__HOA_DON__2725A6E0061CBD2E");

                    b.HasIndex("MaCn");

                    b.HasIndex("MaKh");

                    b.HasIndex("MaNv");

                    b.ToTable("HOA_DON", (string)null);
                });

            modelBuilder.Entity("PetCare_Web.Models.KhachHang", b =>
                {
                    b.Property<string>("MaKh")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("MaKH");

                    b.Property<string>("CapHoiVien")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasDefaultValue("CoBan");

                    b.Property<string>("Cccd")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("CCCD");

                    b.Property<int?>("DiemTichLuy")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("GioiTinh")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateOnly?>("NgaySinh")
                        .HasColumnType("date");

                    b.Property<string>("SoDt")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("SoDT");

                    b.Property<string>("UserName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("MaKh")
                        .HasName("PK__KHACH_HA__2725CF1E1C92EFAA");

                    b.HasIndex("UserName");

                    b.ToTable("KHACH_HANG", (string)null);
                });

            modelBuilder.Entity("PetCare_Web.Models.LichHen", b =>
                {
                    b.Property<string>("MaLichHen")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("GhiChu")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<TimeOnly?>("GioHen")
                        .HasColumnType("time");

                    b.Property<string>("MaBs")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("MaBS");

                    b.Property<string>("MaCn")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("MaCN");

                    b.Property<string>("MaKh")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("MaKH");

                    b.Property<DateOnly?>("NgayHen")
                        .HasColumnType("date");

                    b.Property<string>("TrangThai")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("MaLichHen")
                        .HasName("PK__LICH_HEN__150F264F7D807565");

                    b.HasIndex("MaBs");

                    b.HasIndex("MaCn");

                    b.HasIndex("MaKh");

                    b.ToTable("LICH_HEN", (string)null);
                });

            modelBuilder.Entity("PetCare_Web.Models.LichSuDieuDong", b =>
                {
                    b.Property<string>("MaDieuDong")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<DateOnly>("NgayBatDau")
                        .HasColumnType("date");

                    b.Property<string>("MaCn")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("MaCN");

                    b.Property<DateOnly?>("NgayKetThuc")
                        .HasColumnType("date");

                    b.HasKey("MaDieuDong", "NgayBatDau")
                        .HasName("PK__LICH_SU___8070C1A4096C6650");

                    b.HasIndex("MaCn");

                    b.ToTable("LICH_SU_DIEU_DONG", (string)null);
                });

            modelBuilder.Entity("PetCare_Web.Models.NhanVien", b =>
                {
                    b.Property<string>("MaNv")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("MaNV");

                    b.Property<string>("ChucVu")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("GioiTinh")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal?>("LuongCoBan")
                        .HasColumnType("decimal(18, 0)");

                    b.Property<string>("MaCn")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("MaCN");

                    b.Property<DateOnly>("NgaySinh")
                        .HasColumnType("date");

                    b.Property<DateOnly>("NgayVaoLam")
                        .HasColumnType("date");

                    b.Property<string>("UserName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("MaNv")
                        .HasName("PK__NHAN_VIE__2725D70A7C80624E");

                    b.HasIndex("MaCn");

                    b.HasIndex("UserName");

                    b.ToTable("NHAN_VIEN", (string)null);
                });

            modelBuilder.Entity("PetCare_Web.Models.SanPham", b =>
                {
                    b.Property<string>("MaSp")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("MaSP");

                    b.Property<double?>("GiaBan")
                        .HasColumnType("float");

                    b.Property<string>("LoaiSp")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("LoaiSP");

                    b.Property<string>("TenSp")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("TenSP");

                    b.HasKey("MaSp")
                        .HasName("PK__SAN_PHAM__2725081C821B278D");

                    b.ToTable("SAN_PHAM", (string)null);
                });

            modelBuilder.Entity("PetCare_Web.Models.TaiKhoan", b =>
                {
                    b.Property<string>("UserName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("MatKhau")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("QuyenHan")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("UserName")
                        .HasName("PK__TAI_KHOA__C9F284578A51C119");

                    b.ToTable("TAI_KHOAN", (string)null);
                });

            modelBuilder.Entity("PetCare_Web.Models.ThuCung", b =>
                {
                    b.Property<string>("MaTc")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("MaTC");

                    b.Property<string>("Giong")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Loai")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("MaKh")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("MaKH");

                    b.Property<string>("TenTc")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("TenTC");

                    b.Property<string>("TinhTrangSucKhoe")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("MaTc")
                        .HasName("PK__THU_CUNG__27250068331D9FB9");

                    b.HasIndex("MaKh");

                    b.ToTable("THU_CUNG", (string)null);
                });

            modelBuilder.Entity("PetCare_Web.Models.TonKhoSanPham", b =>
                {
                    b.Property<string>("MaCn")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("MaCN");

                    b.Property<string>("MaSp")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("MaSP");

                    b.Property<DateOnly?>("NgayHetHan")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("NgaySanXuat")
                        .HasColumnType("date");

                    b.Property<int?>("SoLuong")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.HasKey("MaCn", "MaSp")
                        .HasName("PK__TON_KHO___F557DE8F86D1BECB");

                    b.HasIndex("MaSp");

                    b.ToTable("TON_KHO_SAN_PHAM", (string)null);
                });

            modelBuilder.Entity("PetCare_Web.Models.TonKhoVaccine", b =>
                {
                    b.Property<string>("MaCn")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("MaCN");

                    b.Property<string>("MaVc")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("MaVC");

                    b.Property<string>("SoLo")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<DateOnly?>("NgayHetHan")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("NgaySanXuat")
                        .HasColumnType("date");

                    b.Property<int?>("SoLuong")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.HasKey("MaCn", "MaVc", "SoLo")
                        .HasName("PK__TON_KHO___49EBE3C785C7AE0A");

                    b.HasIndex("MaVc");

                    b.ToTable("TON_KHO_VACCINE", (string)null);
                });

            modelBuilder.Entity("PetCare_Web.Models.Vaccine", b =>
                {
                    b.Property<string>("MaVc")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("MaVC");

                    b.Property<double?>("GiaVc")
                        .HasColumnType("float")
                        .HasColumnName("GiaVC");

                    b.Property<string>("LoaiVc")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("LoaiVC");

                    b.Property<string>("TenVc")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("TenVC");

                    b.HasKey("MaVc")
                        .HasName("PK__VACCINE__272510291D0746B1");

                    b.ToTable("VACCINE", (string)null);
                });

            modelBuilder.Entity("PetCare_Web.Models.BangLuongThang", b =>
                {
                    b.HasOne("PetCare_Web.Models.NhanVien", "MaNvNavigation")
                        .WithMany("BangLuongThangs")
                        .HasForeignKey("MaNv")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__BANG_LUONG__MaNV__22751F6C");

                    b.Navigation("MaNvNavigation");
                });

            modelBuilder.Entity("PetCare_Web.Models.BangPhanCa", b =>
                {
                    b.HasOne("PetCare_Web.Models.CaLamViec", "MaCaNavigation")
                        .WithMany("BangPhanCas")
                        .HasForeignKey("MaCa")
                        .IsRequired()
                        .HasConstraintName("FK__BANG_PHAN___MaCa__1CBC4616");

                    b.HasOne("PetCare_Web.Models.NhanVien", "MaNvNavigation")
                        .WithMany("BangPhanCas")
                        .HasForeignKey("MaNv")
                        .IsRequired()
                        .HasConstraintName("FK__BANG_PHAN___MaNV__1BC821DD");

                    b.Navigation("MaCaNavigation");

                    b.Navigation("MaNvNavigation");
                });

            modelBuilder.Entity("PetCare_Web.Models.ChamCong", b =>
                {
                    b.HasOne("PetCare_Web.Models.NhanVien", "MaNvNavigation")
                        .WithMany("ChamCongs")
                        .HasForeignKey("MaNv")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__CHAM_CONG__MaNV__25518C17");

                    b.Navigation("MaNvNavigation");
                });

            modelBuilder.Entity("PetCare_Web.Models.ChiTietDd", b =>
                {
                    b.HasOne("PetCare_Web.Models.NhanVien", "MaNvNavigation")
                        .WithMany("ChiTietDds")
                        .HasForeignKey("MaNv")
                        .IsRequired()
                        .HasConstraintName("FK__CHI_TIET_D__MaNV__4316F928");

                    b.HasOne("PetCare_Web.Models.LichSuDieuDong", "LichSuDieuDong")
                        .WithMany("ChiTietDds")
                        .HasForeignKey("MaDieuDong", "NgayBatDau")
                        .IsRequired()
                        .HasConstraintName("FK__CHI_TIET_DD__440B1D61");

                    b.Navigation("LichSuDieuDong");

                    b.Navigation("MaNvNavigation");
                });

            modelBuilder.Entity("PetCare_Web.Models.ChiTietDvSd", b =>
                {
                    b.HasOne("PetCare_Web.Models.DichVu", "MaDvNavigation")
                        .WithMany("ChiTietDvSds")
                        .HasForeignKey("MaDv")
                        .IsRequired()
                        .HasConstraintName("FK__CHI_TIET_D__MaDV__656C112C");

                    b.HasOne("PetCare_Web.Models.HoaDon", "MaHdNavigation")
                        .WithMany("ChiTietDvSds")
                        .HasForeignKey("MaHd")
                        .IsRequired()
                        .HasConstraintName("FK__CHI_TIET_D__MaHD__6477ECF3");

                    b.Navigation("MaDvNavigation");

                    b.Navigation("MaHdNavigation");
                });

            modelBuilder.Entity("PetCare_Web.Models.ChiTietMuaHang", b =>
                {
                    b.HasOne("PetCare_Web.Models.DvMuaHang", "MaMuaHangNavigation")
                        .WithMany("ChiTietMuaHangs")
                        .HasForeignKey("MaMuaHang")
                        .IsRequired()
                        .HasConstraintName("FK__CHI_TIET___MaMua__0B91BA14");

                    b.HasOne("PetCare_Web.Models.SanPham", "MaSpNavigation")
                        .WithMany("ChiTietMuaHangs")
                        .HasForeignKey("MaSp")
                        .IsRequired()
                        .HasConstraintName("FK__CHI_TIET_M__MaSP__0A9D95DB");

                    b.Navigation("MaMuaHangNavigation");

                    b.Navigation("MaSpNavigation");
                });

            modelBuilder.Entity("PetCare_Web.Models.ChiTietTiem", b =>
                {
                    b.HasOne("PetCare_Web.Models.DvTiemPhongDonLe", "MaTiemNavigation")
                        .WithMany("ChiTietTiems")
                        .HasForeignKey("MaTiem")
                        .IsRequired()
                        .HasConstraintName("FK__CHI_TIET___MaTie__72C60C4A");

                    b.HasOne("PetCare_Web.Models.Vaccine", "MaVcNavigation")
                        .WithMany("ChiTietTiems")
                        .HasForeignKey("MaVc")
                        .IsRequired()
                        .HasConstraintName("FK__CHI_TIET_T__MaVC__73BA3083");

                    b.Navigation("MaTiemNavigation");

                    b.Navigation("MaVcNavigation");
                });

            modelBuilder.Entity("PetCare_Web.Models.ChiTietTiemThang", b =>
                {
                    b.HasOne("PetCare_Web.Models.DvTiemPhongTheoThang", "MaGoiNavigation")
                        .WithMany("ChiTietTiemThangs")
                        .HasForeignKey("MaGoi")
                        .IsRequired()
                        .HasConstraintName("FK__CHI_TIET___MaGoi__7F2BE32F");

                    b.HasOne("PetCare_Web.Models.Vaccine", "MaVcNavigation")
                        .WithMany("ChiTietTiemThangs")
                        .HasForeignKey("MaVc")
                        .IsRequired()
                        .HasConstraintName("FK__CHI_TIET_T__MaVC__7E37BEF6");

                    b.Navigation("MaGoiNavigation");

                    b.Navigation("MaVcNavigation");
                });

            modelBuilder.Entity("PetCare_Web.Models.DanhGium", b =>
                {
                    b.HasOne("PetCare_Web.Models.HoaDon", "MaHdNavigation")
                        .WithMany("DanhGia")
                        .HasForeignKey("MaHd")
                        .IsRequired()
                        .HasConstraintName("FK__DANH_GIA__MaHD__5CD6CB2B");

                    b.HasOne("PetCare_Web.Models.KhachHang", "MaKhNavigation")
                        .WithMany("DanhGia")
                        .HasForeignKey("MaKh")
                        .HasConstraintName("FK__DANH_GIA__MaKH__5BE2A6F2");

                    b.HasOne("PetCare_Web.Models.NhanVien", "MaNvNavigation")
                        .WithMany("DanhGia")
                        .HasForeignKey("MaNv")
                        .HasConstraintName("FK__DANH_GIA__MaNV__5DCAEF64");

                    b.Navigation("MaHdNavigation");

                    b.Navigation("MaKhNavigation");

                    b.Navigation("MaNvNavigation");
                });

            modelBuilder.Entity("PetCare_Web.Models.DichVu", b =>
                {
                    b.HasOne("PetCare_Web.Models.ChiNhanh", "MaCnNavigation")
                        .WithMany("DichVus")
                        .HasForeignKey("MaCn")
                        .IsRequired()
                        .HasConstraintName("FK__DICH_VU__MaCN__619B8048");

                    b.HasOne("PetCare_Web.Models.ThuCung", "MaTcNavigation")
                        .WithMany("DichVus")
                        .HasForeignKey("MaTc")
                        .HasConstraintName("FK__DICH_VU__MaTC__60A75C0F");

                    b.Navigation("MaCnNavigation");

                    b.Navigation("MaTcNavigation");
                });

            modelBuilder.Entity("PetCare_Web.Models.DvKham", b =>
                {
                    b.HasOne("PetCare_Web.Models.NhanVien", "BacSiPhuTrachNavigation")
                        .WithMany("DvKhams")
                        .HasForeignKey("BacSiPhuTrach")
                        .IsRequired()
                        .HasConstraintName("FK__DV_KHAM__BacSiPh__693CA210");

                    b.HasOne("PetCare_Web.Models.DichVu", "MaKhamNavigation")
                        .WithOne("DvKham")
                        .HasForeignKey("PetCare_Web.Models.DvKham", "MaKham")
                        .IsRequired()
                        .HasConstraintName("FK__DV_KHAM__MaKham__6A30C649");

                    b.Navigation("BacSiPhuTrachNavigation");

                    b.Navigation("MaKhamNavigation");
                });

            modelBuilder.Entity("PetCare_Web.Models.DvMuaHang", b =>
                {
                    b.HasOne("PetCare_Web.Models.DichVu", "MaMuaHangNavigation")
                        .WithOne("DvMuaHang")
                        .HasForeignKey("PetCare_Web.Models.DvMuaHang", "MaMuaHang")
                        .IsRequired()
                        .HasConstraintName("FK__DV_MUA_HA__MaMua__05D8E0BE");

                    b.HasOne("PetCare_Web.Models.NhanVien", "NhanVienBanHangNavigation")
                        .WithMany("DvMuaHangs")
                        .HasForeignKey("NhanVienBanHang")
                        .IsRequired()
                        .HasConstraintName("FK__DV_MUA_HA__NhanV__04E4BC85");

                    b.Navigation("MaMuaHangNavigation");

                    b.Navigation("NhanVienBanHangNavigation");
                });

            modelBuilder.Entity("PetCare_Web.Models.DvTiemPhongDonLe", b =>
                {
                    b.HasOne("PetCare_Web.Models.NhanVien", "BacSiPhuTrachNavigation")
                        .WithMany("DvTiemPhongDonLes")
                        .HasForeignKey("BacSiPhuTrach")
                        .IsRequired()
                        .HasConstraintName("FK__DV_TIEM_P__BacSi__6E01572D");

                    b.HasOne("PetCare_Web.Models.DichVu", "MaTiemNavigation")
                        .WithOne("DvTiemPhongDonLe")
                        .HasForeignKey("PetCare_Web.Models.DvTiemPhongDonLe", "MaTiem")
                        .IsRequired()
                        .HasConstraintName("FK__DV_TIEM_P__MaTie__6D0D32F4");

                    b.Navigation("BacSiPhuTrachNavigation");

                    b.Navigation("MaTiemNavigation");
                });

            modelBuilder.Entity("PetCare_Web.Models.DvTiemPhongTheoThang", b =>
                {
                    b.HasOne("PetCare_Web.Models.NhanVien", "BacSiPhuTrachNavigation")
                        .WithMany("DvTiemPhongTheoThangs")
                        .HasForeignKey("BacSiPhuTrach")
                        .HasConstraintName("FK__DV_TIEM_P__BacSi__797309D9");

                    b.HasOne("PetCare_Web.Models.DichVu", "MaGoiNavigation")
                        .WithOne("DvTiemPhongTheoThang")
                        .HasForeignKey("PetCare_Web.Models.DvTiemPhongTheoThang", "MaGoi")
                        .IsRequired()
                        .HasConstraintName("FK__DV_TIEM_P__MaGoi__787EE5A0");

                    b.Navigation("BacSiPhuTrachNavigation");

                    b.Navigation("MaGoiNavigation");
                });

            modelBuilder.Entity("PetCare_Web.Models.HoaDon", b =>
                {
                    b.HasOne("PetCare_Web.Models.ChiNhanh", "MaCnNavigation")
                        .WithMany("HoaDons")
                        .HasForeignKey("MaCn")
                        .IsRequired()
                        .HasConstraintName("FK__HOA_DON__MaCN__5629CD9C");

                    b.HasOne("PetCare_Web.Models.KhachHang", "MaKhNavigation")
                        .WithMany("HoaDons")
                        .HasForeignKey("MaKh")
                        .IsRequired()
                        .HasConstraintName("FK__HOA_DON__MaKH__5535A963");

                    b.HasOne("PetCare_Web.Models.NhanVien", "MaNvNavigation")
                        .WithMany("HoaDons")
                        .HasForeignKey("MaNv")
                        .IsRequired()
                        .HasConstraintName("FK__HOA_DON__MaNV__5441852A");

                    b.Navigation("MaCnNavigation");

                    b.Navigation("MaKhNavigation");

                    b.Navigation("MaNvNavigation");
                });

            modelBuilder.Entity("PetCare_Web.Models.KhachHang", b =>
                {
                    b.HasOne("PetCare_Web.Models.TaiKhoan", "UserNameNavigation")
                        .WithMany("KhachHangs")
                        .HasForeignKey("UserName")
                        .HasConstraintName("FK__KHACH_HAN__UserN__4BAC3F29");

                    b.Navigation("UserNameNavigation");
                });

            modelBuilder.Entity("PetCare_Web.Models.LichHen", b =>
                {
                    b.HasOne("PetCare_Web.Models.NhanVien", "MaBsNavigation")
                        .WithMany("LichHens")
                        .HasForeignKey("MaBs")
                        .HasConstraintName("FK__LICH_HEN__MaBS__29221CFB");

                    b.HasOne("PetCare_Web.Models.ChiNhanh", "MaCnNavigation")
                        .WithMany("LichHens")
                        .HasForeignKey("MaCn")
                        .HasConstraintName("FK__LICH_HEN__MaCN__2A164134");

                    b.HasOne("PetCare_Web.Models.KhachHang", "MaKhNavigation")
                        .WithMany("LichHens")
                        .HasForeignKey("MaKh")
                        .HasConstraintName("FK__LICH_HEN__MaKH__282DF8C2");

                    b.Navigation("MaBsNavigation");

                    b.Navigation("MaCnNavigation");

                    b.Navigation("MaKhNavigation");
                });

            modelBuilder.Entity("PetCare_Web.Models.LichSuDieuDong", b =>
                {
                    b.HasOne("PetCare_Web.Models.ChiNhanh", "MaCnNavigation")
                        .WithMany("LichSuDieuDongs")
                        .HasForeignKey("MaCn")
                        .IsRequired()
                        .HasConstraintName("FK__LICH_SU_DI__MaCN__403A8C7D");

                    b.Navigation("MaCnNavigation");
                });

            modelBuilder.Entity("PetCare_Web.Models.NhanVien", b =>
                {
                    b.HasOne("PetCare_Web.Models.ChiNhanh", "MaCnNavigation")
                        .WithMany("NhanViens")
                        .HasForeignKey("MaCn")
                        .IsRequired()
                        .HasConstraintName("FK__NHAN_VIEN__MaCN__3C69FB99");

                    b.HasOne("PetCare_Web.Models.TaiKhoan", "UserNameNavigation")
                        .WithMany("NhanViens")
                        .HasForeignKey("UserName")
                        .HasConstraintName("FK__NHAN_VIEN__UserN__3D5E1FD2");

                    b.Navigation("MaCnNavigation");

                    b.Navigation("UserNameNavigation");
                });

            modelBuilder.Entity("PetCare_Web.Models.ThuCung", b =>
                {
                    b.HasOne("PetCare_Web.Models.KhachHang", "MaKhNavigation")
                        .WithMany("ThuCungs")
                        .HasForeignKey("MaKh")
                        .IsRequired()
                        .HasConstraintName("FK__THU_CUNG__MaKH__4E88ABD4");

                    b.Navigation("MaKhNavigation");
                });

            modelBuilder.Entity("PetCare_Web.Models.TonKhoSanPham", b =>
                {
                    b.HasOne("PetCare_Web.Models.ChiNhanh", "MaCnNavigation")
                        .WithMany("TonKhoSanPhams")
                        .HasForeignKey("MaCn")
                        .IsRequired()
                        .HasConstraintName("FK__TON_KHO_SA__MaCN__10566F31");

                    b.HasOne("PetCare_Web.Models.SanPham", "MaSpNavigation")
                        .WithMany("TonKhoSanPhams")
                        .HasForeignKey("MaSp")
                        .IsRequired()
                        .HasConstraintName("FK__TON_KHO_SA__MaSP__114A936A");

                    b.Navigation("MaCnNavigation");

                    b.Navigation("MaSpNavigation");
                });

            modelBuilder.Entity("PetCare_Web.Models.TonKhoVaccine", b =>
                {
                    b.HasOne("PetCare_Web.Models.ChiNhanh", "MaCnNavigation")
                        .WithMany("TonKhoVaccines")
                        .HasForeignKey("MaCn")
                        .IsRequired()
                        .HasConstraintName("FK__TON_KHO_VA__MaCN__160F4887");

                    b.HasOne("PetCare_Web.Models.Vaccine", "MaVcNavigation")
                        .WithMany("TonKhoVaccines")
                        .HasForeignKey("MaVc")
                        .IsRequired()
                        .HasConstraintName("FK__TON_KHO_VA__MaVC__17036CC0");

                    b.Navigation("MaCnNavigation");

                    b.Navigation("MaVcNavigation");
                });

            modelBuilder.Entity("PetCare_Web.Models.CaLamViec", b =>
                {
                    b.Navigation("BangPhanCas");
                });

            modelBuilder.Entity("PetCare_Web.Models.ChiNhanh", b =>
                {
                    b.Navigation("DichVus");

                    b.Navigation("HoaDons");

                    b.Navigation("LichHens");

                    b.Navigation("LichSuDieuDongs");

                    b.Navigation("NhanViens");

                    b.Navigation("TonKhoSanPhams");

                    b.Navigation("TonKhoVaccines");
                });

            modelBuilder.Entity("PetCare_Web.Models.DichVu", b =>
                {
                    b.Navigation("ChiTietDvSds");

                    b.Navigation("DvKham");

                    b.Navigation("DvMuaHang");

                    b.Navigation("DvTiemPhongDonLe");

                    b.Navigation("DvTiemPhongTheoThang");
                });

            modelBuilder.Entity("PetCare_Web.Models.DvMuaHang", b =>
                {
                    b.Navigation("ChiTietMuaHangs");
                });

            modelBuilder.Entity("PetCare_Web.Models.DvTiemPhongDonLe", b =>
                {
                    b.Navigation("ChiTietTiems");
                });

            modelBuilder.Entity("PetCare_Web.Models.DvTiemPhongTheoThang", b =>
                {
                    b.Navigation("ChiTietTiemThangs");
                });

            modelBuilder.Entity("PetCare_Web.Models.HoaDon", b =>
                {
                    b.Navigation("ChiTietDvSds");

                    b.Navigation("DanhGia");
                });

            modelBuilder.Entity("PetCare_Web.Models.KhachHang", b =>
                {
                    b.Navigation("DanhGia");

                    b.Navigation("HoaDons");

                    b.Navigation("LichHens");

                    b.Navigation("ThuCungs");
                });

            modelBuilder.Entity("PetCare_Web.Models.LichSuDieuDong", b =>
                {
                    b.Navigation("ChiTietDds");
                });

            modelBuilder.Entity("PetCare_Web.Models.NhanVien", b =>
                {
                    b.Navigation("BangLuongThangs");

                    b.Navigation("BangPhanCas");

                    b.Navigation("ChamCongs");

                    b.Navigation("ChiTietDds");

                    b.Navigation("DanhGia");

                    b.Navigation("DvKhams");

                    b.Navigation("DvMuaHangs");

                    b.Navigation("DvTiemPhongDonLes");

                    b.Navigation("DvTiemPhongTheoThangs");

                    b.Navigation("HoaDons");

                    b.Navigation("LichHens");
                });

            modelBuilder.Entity("PetCare_Web.Models.SanPham", b =>
                {
                    b.Navigation("ChiTietMuaHangs");

                    b.Navigation("TonKhoSanPhams");
                });

            modelBuilder.Entity("PetCare_Web.Models.TaiKhoan", b =>
                {
                    b.Navigation("KhachHangs");

                    b.Navigation("NhanViens");
                });

            modelBuilder.Entity("PetCare_Web.Models.ThuCung", b =>
                {
                    b.Navigation("DichVus");
                });

            modelBuilder.Entity("PetCare_Web.Models.Vaccine", b =>
                {
                    b.Navigation("ChiTietTiemThangs");

                    b.Navigation("ChiTietTiems");

                    b.Navigation("TonKhoVaccines");
                });
#pragma warning restore 612, 618
        }
    }
}
